version: '2'
services:
  data:
    build: .
  mysql:
    image: mariadb
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - .:/docker-entrypoint-initdb.d
    volumes_from:
      - data

  seleniumhub:
    container_name: selenium_hub
    image: selenium/hub
    ports:
      - "4444:4444"
    expose:
      - "4444"
    depends_on:
      - mysql
    links:
      - mysql

  chromenode:
    container_name: chromenode
    image: selenium/node-chrome-debug
    links:
      - seleniumhub:hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub
      - HUB_PORT_4444_TCP_PORT=4444
    expose:
      - "5555"

