version: '2'
services:

  mysql:
    image: mariadb
    ports:
    - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb

  seleniumhub:
    image: selenium/hub
    ports:
    - 4444:4444
    depends_on:
      - mysql
    links:
      - mysql

  chromenode:
    image: selenium/node-chrome-debug
    ports:
    - 4578
    links:
    - seleniumhub:hub

  maven:
    image: 3.6.0-jdk-11

volumes:
  mysql_data: