version: '2'
services:
  data:
    build: data/.
  mysql:
    image: mariadb
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    volumes_from:
      - data

  seleniumhub:
    image: selenium/hub
    ports:
    - 4444:4444
    depends_on:
      - mysql
    links:
      - mysql

  chromenode:
    image: selenium/node-chrome-debug
    ports:
    - 4578
    links:
    - seleniumhub:hub

