version: '2'
services:
  seleniumhub:
    image: selenium/hub
    ports:
    - 4444:4444

  chromenode:
    image: selenium/node-chrome-debug
    ports:
    - 4578
    links:
    - seleniumhub:hub

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'