compile:
   dockerfile: .dockerfile
   project_name: dockerMvnRepo
services:
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=admin
    networks:
    - compose-net
    expose:
    - 3306

  java-unit:
    image: java:11-jdk
    working_dir: /src

seleniumhub:
  image: selenium/hub
  ports:
  - 4444:4444

chromenode:
  image: selenium/node-chrome-debug
  ports:
  - 4578
  links:
  - seleniumhub:hub